### ISSUE TITLE
Status is "up" if nothing else

### ISSUE THREAD

**Issue by teemow** [giantswarm/user-config#2]
(@teemow asked me to report this.)

https://git.giantswarm.io/giantswarm/user-config/blob/master/status.go#L28 shows that AggregateStatus returns "up" if no other condition matches.

It might be more robust to return an unknown status if no other condition matches.

Original Author: @marian
Created at 09-11-2014 10:58:07
Gitlab: [giantswarm/user-config!2](https://git.giantswarm.io/giantswarm/user-config/issues/2)

**Comment by zyndiecate** [comment]
Is this issue still valid? Do we need to work on this stability wise?

**Comment by ZeissS** [comment]
No, we have the container-states repo now with a slighlt better logic.
